"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState, type FormEvent } from "react";
import { usePathname, useRouter, useSearchParams } from "next/navigation";
import type { ApplicationStage } from "@prisma/client";
import { updateApplicationStage } from "@/app/actions";
import { Badge } from "@/components/cards";
import { DeleteJobForm } from "@/components/delete-job-form";
import { formatDate } from "@/lib/format";
import { getStageDisplayLabel, normalizeApplicationStage, stageOptions } from "@/lib/constants";

type JobItem = {
  id: string; companyName: string; roleTitle: string; city: string | null; seniority: string | null;
  sourceName: string | null; parsedSummary: string | null; rawContent: string; needsReview: boolean;
  skills: string; status: ApplicationStage; updatedAt: Date;
  application: { id: string; currentStage: ApplicationStage; submissionChannel: string | null; nextAction: string | null; note: string | null; updatedAt: Date } | null;
};

export function JobsListClient({ jobs, initialView = "table", initialQuery = "", initialStatus = "ALL", initialCity = "ALL", initialSource = "ALL" }: {
  jobs: JobItem[]; initialView?: "table" | "board"; initialQuery?: string; initialStatus?: string; initialCity?: string; initialSource?: string;
}) {
  const router = useRouter(); const pathname = usePathname(); const searchParams = useSearchParams();
  const [items, setItems] = useState(jobs); const [query, setQuery] = useState(initialQuery); const [status, setStatus] = useState(initialStatus); const [city, setCity] = useState(initialCity); const [source, setSource] = useState(initialSource); const [view, setView] = useState<"table" | "board">(initialView);
  const cities = useMemo(() => options(items.map((job) => job.city || "地点待确认")), [items]);
  const sources = useMemo(() => options(items.map((job) => job.sourceName || "主动导入")), [items]);
  const filtered = useMemo(() => items.filter((job) => {
    const stage = normalizeApplicationStage(job.application?.currentStage || job.status);
    const haystack = [job.companyName, job.roleTitle, job.city, job.sourceName, job.application?.submissionChannel, job.application?.nextAction, job.application?.note, job.parsedSummary, job.skills].join(" ").toLowerCase();
    return (!query.trim() || haystack.includes(query.trim().toLowerCase())) && (status === "ALL" || stage === status) && (city === "ALL" || (job.city || "地点待确认") === city) && (source === "ALL" || (job.sourceName || "主动导入") === source);
  }), [items, query, status, city, source]);

  useEffect(() => { const params = new URLSearchParams(searchParams.toString()); setParam(params, "view", view === "board" ? "board" : ""); setParam(params, "q", query.trim()); setParam(params, "status", status === "ALL" ? "" : status); setParam(params, "city", city === "ALL" ? "" : city); setParam(params, "source", source === "ALL" ? "" : source); const next = params.toString(); if (next !== searchParams.toString()) router.replace(next ? `${pathname}?${next}` : pathname, { scroll: false }); }, [city, pathname, query, router, searchParams, source, status, view]);

  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const id = String(data.get("applicationId") || ""); const stage = data.get("stage") as ApplicationStage | null; if (!id || !stage) return; await updateApplicationStage(data); setItems((current) => current.map((job) => job.application?.id === id ? { ...job, status: stage, updatedAt: new Date(), application: { ...job.application, currentStage: stage, submissionChannel: String(data.get("submissionChannel") || "") || null, nextAction: String(data.get("nextAction") || "") || null, note: String(data.get("note") || "") || null, updatedAt: new Date() } } : job)); }
  const remove = (id: string) => setItems((current) => current.filter((job) => job.id !== id));

  return <div className="space-y-3"><div className="grid gap-2.5 xl:grid-cols-[minmax(220px,1.35fr)_140px_140px_160px_148px]"><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="搜索岗位、公司、进度、事件或下一步" className="h-10 w-full rounded-xl border border-line bg-white px-3.5 text-sm outline-none" /><select value={status} onChange={(e) => setStatus(e.target.value)} className="h-10 rounded-xl border border-line bg-white px-3 text-sm"><option value="ALL">全部进度</option>{stageOptions.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select><select value={city} onChange={(e) => setCity(e.target.value)} className="h-10 rounded-xl border border-line bg-white px-3 text-sm"><option value="ALL">全部 Base</option>{cities.map((x) => <option key={x}>{x}</option>)}</select><select value={source} onChange={(e) => setSource(e.target.value)} className="h-10 rounded-xl border border-line bg-white px-3 text-sm"><option value="ALL">全部来源</option>{sources.map((x) => <option key={x}>{x}</option>)}</select><div className="grid h-10 grid-cols-2 rounded-xl border border-line bg-white p-1 text-sm"><button onClick={() => setView("table")} className={view === "table" ? "rounded-lg bg-ink text-white" : "text-slate-600"}>列表</button><button onClick={() => setView("board")} className={view === "board" ? "rounded-lg bg-ink text-white" : "text-slate-600"}>看板</button></div></div>{filtered.length === 0 ? <EmptyState /> : view === "table" ? <div className="overflow-x-auto rounded-3xl border border-line bg-white shadow-card"><div className="min-w-[1080px]"><div className="grid grid-cols-[220px_130px_130px_190px_240px_130px_120px] border-b border-line bg-slate-50 px-4 py-2 text-[11px] font-medium uppercase tracking-[.14em] text-slate-400"><div>岗位</div><div>Base</div><div>进度</div><div>下一步</div><div>事件与备注</div><div>更新</div><div>操作</div></div>{filtered.map((job) => <JobRow key={job.id} job={job} onSave={save} onDeleted={remove} />)}</div></div> : <div className="grid gap-3 xl:grid-cols-4 2xl:grid-cols-5">{stageOptions.map((stage) => <section key={stage.value} className="min-h-[220px] rounded-3xl border border-line bg-white p-3 shadow-card"><div className="mb-3 flex items-center justify-between"><h2 className="font-semibold text-ink">{stage.label}</h2><Badge>{filtered.filter((job) => normalizeApplicationStage(job.application?.currentStage || job.status) === stage.value).length}</Badge></div><div className="space-y-3">{filtered.filter((job) => normalizeApplicationStage(job.application?.currentStage || job.status) === stage.value).map((job) => <JobCard key={job.id} job={job} onSave={save} onDeleted={remove} />)}</div></section>)}</div>}</div>;
}

function JobRow({ job, onSave, onDeleted }: { job: JobItem; onSave: (e: FormEvent<HTMLFormElement>) => Promise<void>; onDeleted: (id: string) => void }) { return <JobEditor job={job} onSave={onSave} onDeleted={onDeleted} className="grid grid-cols-[220px_130px_130px_190px_240px_130px_120px] items-start gap-0 border-b border-line px-4 py-3 text-sm" />; }
function JobCard({ job, onSave, onDeleted }: { job: JobItem; onSave: (e: FormEvent<HTMLFormElement>) => Promise<void>; onDeleted: (id: string) => void }) { return <JobEditor job={job} onSave={onSave} onDeleted={onDeleted} className="rounded-2xl border border-line bg-panel p-3 text-sm" card />; }
function JobEditor({ job, onSave, onDeleted, className, card = false }: { job: JobItem; onSave: (e: FormEvent<HTMLFormElement>) => Promise<void>; onDeleted: (id: string) => void; className: string; card?: boolean }) {
  const ref = useRef<HTMLFormElement>(null); const app = job.application;
  const fields = <><div className={card ? "mt-2" : ""}><label className="sr-only">进度</label>{app ? <select name="stage" defaultValue={normalizeApplicationStage(app.currentStage)} onChange={() => ref.current?.requestSubmit()} className="h-9 w-full rounded-xl border border-line bg-white px-2 text-sm">{stageOptions.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</select> : <span className="text-slate-500">{getStageDisplayLabel(job.status)}</span>}</div>{app ? <><div className={card ? "mt-2" : ""}><input name="nextAction" defaultValue={app.nextAction || ""} onBlur={() => ref.current?.requestSubmit()} placeholder="下一步" className="h-9 w-full rounded-xl border border-line bg-white px-3 text-sm" /></div><div className={card ? "mt-2" : ""}><textarea name="note" defaultValue={app.note || ""} onBlur={() => ref.current?.requestSubmit()} placeholder="事件、联系人或个人判断" rows={card ? 2 : 3} className="w-full resize-none rounded-xl border border-line bg-white px-3 py-2 text-sm" /><input name="submissionChannel" defaultValue={app.submissionChannel || ""} onBlur={() => ref.current?.requestSubmit()} placeholder="投递渠道" className="mt-2 h-8 w-full rounded-xl border border-line bg-white px-3 text-sm" /></div></> : <><div className={card ? "mt-2" : ""}>尚未开始</div><div className={card ? "mt-2" : ""}>-</div></>}</>;
  if (card) return <form ref={ref} onSubmit={onSave} className={className}>{app ? <input type="hidden" name="applicationId" value={app.id} /> : null}<Link href={`/jobs/${job.id}`} className="font-semibold text-ink underline-offset-4 hover:underline">{job.roleTitle}</Link><p className="mt-1 text-slate-500">{job.companyName} · {job.city || "地点待确认"}</p>{fields}<div className="mt-3 flex gap-2"><Link href="/tailor" className="text-xs font-medium text-accent">Agent 准备</Link><DeleteJobForm jobLeadId={job.id} onDeleted={onDeleted} /></div></form>;
  return <form ref={ref} onSubmit={onSave} className={className}>{app ? <input type="hidden" name="applicationId" value={app.id} /> : null}<div><Link href={`/jobs/${job.id}`} className="font-semibold text-ink underline-offset-4 hover:underline">{job.roleTitle}</Link><div className="mt-1 text-slate-500">{job.companyName}{job.needsReview ? <Badge>待确认</Badge> : null}</div></div><div>{job.city || "待确认"}</div>{fields}<div className="text-xs text-slate-500">{formatDate(job.updatedAt)}</div><div className="flex flex-col items-start gap-2"><Link href="/tailor" className="text-xs font-medium text-accent">Agent 准备</Link><DeleteJobForm jobLeadId={job.id} onDeleted={onDeleted} /></div></form>;
}
function EmptyState() { return <div className="rounded-3xl border border-dashed border-line bg-white p-6 text-center text-sm text-slate-500">当前筛选条件下还没有岗位记录。</div>; }
function options(values: string[]) { return [...new Set(values.filter(Boolean))].sort((a, b) => a.localeCompare(b)); }
function setParam(params: URLSearchParams, key: string, value: string) { if (value) params.set(key, value); else params.delete(key); }
