ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'WRITTEN_TEST';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'AI_INTERVIEW';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'FIRST_INTERVIEW';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'SECOND_INTERVIEW';
ALTER TYPE "EventType" ADD VALUE IF NOT EXISTS 'THIRD_INTERVIEW';
